site_name: Git Package Management
docs_dir: core/components/gitpackagemanagement/docs
site_dir: core/components/gitpackagemanagement/site
repo_url: https://github.com/TheBoxer/Git-Package-Management
pages:
- [index.md, Home]
- [directory-structure.md, General, Directory structure]
- [installation.md, General, Installation]
- [system-settings.md, General, System settings]
- [config/general.md, Config, General]
- [config/package.md, Config, Package]
- [config/database.md, Config, Database]
- [config/extension-package.md, Config, Extension package]
- [config/build.md, Config, Build]
- [config/examples.md, Config, Examples]
theme: readthedocs